// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Potluck_Party_API.Data;

#nullable disable

namespace Potluck_Party_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230627120852_creating_database_and_tables")]
    partial class creating_database_and_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Potluck_Party_API.Models.Dish", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Food")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("Potluck_Party_API.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Potluck_Party_API.Models.Dish", b =>
                {
                    b.HasOne("Potluck_Party_API.Models.User", "User")
                        .WithOne("Dish")
                        .HasForeignKey("Potluck_Party_API.Models.Dish", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Potluck_Party_API.Models.User", b =>
                {
                    b.Navigation("Dish")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
